DELETE FROM mangos_string WHERE entry BETWEEN 11100 AND 11199;

INSERT INTO `mangos_string` VALUES ('11100', '%s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('11101', '%s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('11102', '%s\'s mailbox is full!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('11103', 'GM Areatrigger announcement ON', '', '', '', '', '', '', '', '');
INSERT INTO `mangos_string` VALUES ('11104', 'GM Areatrigger announcement OFF.', '', '', '', '', '', '', '', '');
INSERT INTO `mangos_string` VALUES ('11105', 'You just entered Areatrigger %u', '', '', '', '', '', '', '', '');
INSERT INTO `mangos_string` VALUES ('11106', 'GM Haxors announcement ON.', '', '', '', '', '', '', '', '');
INSERT INTO `mangos_string` VALUES ('11107', 'GM Haxors announcement OFF.', '', '', '', '', '', '', '', '');
INSERT INTO `mangos_string` VALUES ('11108', '|cffFF0000Haxor?! |cffFF0077 Acc: %u Name: %s Impact: %u [|cff00FF00 %s|r]', '', '', '', '', '', '', '', '');
INSERT INTO `mangos_string` VALUES ('11109', 'Your chat in global channels has been disabled for %u minutes - possibly due to spam or incorrect channel use. If you have no idea, read the rules.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('11110', '\'%s\' in the opposing team has the same IP like you, you are not rewarded Arena Points. (aka win trading sucks!)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('11111', 'Your chat in global channels has been enabled.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('11112', 'You have disabled %s\'s global channel chat for %u minutes.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('11113', 'You have enabled %s\'s global channel chat.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('11114', 'You must wait %s before you can speak in global channels again.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('11115', 'Your |cffFF0000bad points|r score was just increased to |cffFF0000%u of %u (%.1f %%)|r. Be careful - if it gets higher, |cffFF0000bad things|r will happen! Stick to the rules please.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('11116', '|cffFF7005You currently have |cffFF0000%u of %u bad points|cffFF7005. You lose points over time, even while offline, after not violating any rules for some time. Stick to the rules, please!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('11117', '\'%s\' has no record in database', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('11118', '<no extra reason given>', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('11119', 'You punished %s for \'%s\'; has now %u of %u points (%.1f %%).', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('11120', '|cffFF7005Penalty Points: %u|r', null, null, null, null, null, null, null, null);
